version: '3'

services:
  app:
    build: .
    environment:
      MONGO_URL: mongodb://mongo:27017/
      ES_INDEX: estabelecimentos9
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - my-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - my-network

  elasticsearch:
    image: bitnami/elasticsearch
    restart: always
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
